function cfg = bearing_config()
%BEARING_CONFIG Central settings for the bearing analysis workflow.

analysisFolder = fileparts(mfilename('fullpath'));
projectRoot = fileparts(analysisFolder);

cfg.projectRoot = projectRoot;
cfg.dataFolder = fullfile(projectRoot, 'data');
cfg.outputFolder = fullfile(projectRoot, 'outputs');
cfg.figureFolder = fullfile(cfg.outputFolder, 'figures');
cfg.tableFolder = fullfile(cfg.outputFolder, 'tables');
cfg.modelFolder = fullfile(cfg.outputFolder, 'models');
cfg.reportFolder = fullfile(cfg.outputFolder, 'report');

cfg.fs = 200000;
cfg.durationSeconds = 10;
cfg.windowSeconds = 0.10;
cfg.overlap = 0.50;

cfg.healthCodes = {'H', 'I', 'O'};
cfg.healthNames = {'Healthy', 'Inner race fault', 'Outer race fault'};

cfg.speedCodes = {'A', 'B', 'C', 'D'};
cfg.speedNames = { ...
    'Increasing speed', ...
    'Decreasing speed', ...
    'Increasing then decreasing speed', ...
    'Decreasing then increasing speed'};

cfg.vibrationFeatureNames = { ...
    'rms_value', ...
    'std_value', ...
    'variance_value', ...
    'mean_abs', ...
    'peak_to_peak', ...
    'crest_factor', ...
    'impulse_factor', ...
    'shape_factor', ...
    'skewness_value', ...
    'kurtosis_value', ...
    'energy_value', ...
    'spectral_energy', ...
    'spectral_centroid', ...
    'low_freq_ratio', ...
    'high_freq_ratio', ...
    'rms_per_speed'};

cfg.speedFeatureNames = { ...
    'speed_mean', ...
    'speed_std', ...
    'speed_start', ...
    'speed_end', ...
    'speed_slope'};

cfg.featureNames = [cfg.vibrationFeatureNames, cfg.speedFeatureNames];

cfg.severityFeatureNames = { ...
    'rms_value', ...
    'peak_to_peak', ...
    'crest_factor', ...
    'kurtosis_value', ...
    'energy_value', ...
    'spectral_energy', ...
    'high_freq_ratio', ...
    'rms_per_speed'};

cfg.representativeFiles = { ...
    'H-A-3.mat', ...
    'I-A-3.mat', ...
    'O-A-3.mat'};
end
