function figurePaths = make_classification_plots(cfg, classification)
%MAKE_CLASSIFICATION_PLOTS Create classification result figures.

figurePaths = strings(0, 1);

outPath = fullfile(cfg.figureFolder, 'confusion_health_window_knn.png');
plot_confusion_matrix_plain( ...
    classification.health.windowKnnMetrics.confusion, ...
    cfg.healthNames, ...
    'Health classification - window level, 5-NN', ...
    outPath);
figurePaths(end+1, 1) = string(outPath);

outPath = fullfile(cfg.figureFolder, 'confusion_health_file_knn.png');
plot_confusion_matrix_plain( ...
    classification.health.fileKnnMetrics.confusion, ...
    cfg.healthNames, ...
    'Health classification - file level, 5-NN', ...
    outPath);
figurePaths(end+1, 1) = string(outPath);

outPath = fullfile(cfg.figureFolder, 'confusion_speed_file_knn.png');
plot_confusion_matrix_plain( ...
    classification.speed.fileMetrics.confusion, ...
    cfg.speedNames, ...
    'Speed pattern classification - file level, 5-NN', ...
    outPath);
figurePaths(end+1, 1) = string(outPath);

outPath = fullfile(cfg.figureFolder, 'confusion_12_case_file_knn.png');
plot_confusion_matrix_plain( ...
    classification.case.fileMetrics.confusion, ...
    cellstr(classification.case.fileMetrics.classNames), ...
    '12-case classification - file level, 5-NN', ...
    outPath);
figurePaths(end+1, 1) = string(outPath);
end
