function fileSummary = summarize_file_features(featureTable, cfg)
%SUMMARIZE_FILE_FEATURES Average window features into one row per file.

files = unique(featureTable.file, 'stable');
featureCount = numel(cfg.featureNames);

fileCol = strings(numel(files), 1);
baseNameCol = strings(numel(files), 1);
healthCodeCol = strings(numel(files), 1);
healthNameCol = strings(numel(files), 1);
speedCodeCol = strings(numel(files), 1);
speedNameCol = strings(numel(files), 1);
caseNameCol = strings(numel(files), 1);
healthIndexCol = zeros(numel(files), 1);
speedIndexCol = zeros(numel(files), 1);
caseIndexCol = zeros(numel(files), 1);
trialCol = zeros(numel(files), 1);
windowCountCol = zeros(numel(files), 1);
meanFeatures = zeros(numel(files), featureCount);
stdFeatures = zeros(numel(files), featureCount);

for i = 1:numel(files)
    mask = featureTable.file == files(i);
    first = find(mask, 1);

    fileCol(i) = featureTable.file(first);
    baseNameCol(i) = featureTable.base_name(first);
    healthCodeCol(i) = featureTable.health_code(first);
    healthNameCol(i) = featureTable.health_name(first);
    speedCodeCol(i) = featureTable.speed_code(first);
    speedNameCol(i) = featureTable.speed_name(first);
    caseNameCol(i) = featureTable.case_name(first);
    healthIndexCol(i) = featureTable.health_index(first);
    speedIndexCol(i) = featureTable.speed_index(first);
    caseIndexCol(i) = featureTable.case_index(first);
    trialCol(i) = featureTable.trial(first);
    windowCountCol(i) = sum(mask);

    X = table2array(featureTable(mask, cfg.featureNames));
    meanFeatures(i, :) = mean(X, 1);
    stdFeatures(i, :) = std(X, 0, 1);
end

fileSummary = table( ...
    fileCol, ...
    baseNameCol, ...
    healthCodeCol, ...
    healthIndexCol, ...
    healthNameCol, ...
    speedCodeCol, ...
    speedIndexCol, ...
    speedNameCol, ...
    caseIndexCol, ...
    caseNameCol, ...
    trialCol, ...
    windowCountCol, ...
    'VariableNames', { ...
    'file', ...
    'base_name', ...
    'health_code', ...
    'health_index', ...
    'health_name', ...
    'speed_code', ...
    'speed_index', ...
    'speed_name', ...
    'case_index', ...
    'case_name', ...
    'trial', ...
    'window_count'});

for j = 1:featureCount
    fileSummary.([cfg.featureNames{j}, '_mean']) = meanFeatures(:, j);
    fileSummary.([cfg.featureNames{j}, '_std']) = stdFeatures(:, j);
end
end
